In [227]:
import pandas as pd
 
import os

current_directory = os.getcwd()

# First, we focus on the US_OIL dataframe. We fill NA values with 0 and select important features.

df_US_OIL = pd.read_excel(current_directory+"\\US OIL Dataset.xlsx", sheet_name = 'Data 2')

df_US_OIL.columns = df_US_OIL.iloc[1]
df_US_OIL = df_US_OIL[2:].reset_index(drop = True)
df_US_OIL['Date'] = pd.to_datetime(df_US_OIL['Date']).dt.strftime('%Y-%m')
df_US_OIL = df_US_OIL.fillna(0)
df_US_OIL

1,Date,U.S. Field Production of Crude Oil (Thousand Barrels),U.S. Transfers to Crude Oil Supply of Crude Oil(Thousand Barrels),U.S. Imports of Crude Oil (Thousand Barrels),U.S. Supply Adjustment of Crude Oil (Thousand Barrels),U.S. Crude Oil Stock Change (Thousand Barrels),U.S. Refinery and Blender Net Input of Crude Oil (Thousand Barrels),U.S. Exports of Crude Oil (Thousand Barrels),U.S. Product Supplied of Crude Oil (Thousand Barrels),U.S. Ending Stocks of Crude Oil (Thousand Barrels)
0,1920-01,34008,0,6294,0,0,0,469,0,0
1,1920-02,33193,0,4940,0,0,0,853,0,0
2,1920-03,36171,0,6503,0,0,0,892,0,0
3,1920-04,34945,0,6186,0,0,0,693,0,0
4,1920-05,36622,0,6966,0,0,0,761,0,0
...,...,...,...,...,...,...,...,...,...,...
1239,2023-04,379500,13873,185821,3259,-13007,475195,120265,0,823605
1240,2023-05,393513,13376,200556,4019,-8419,502416,117467,0,815186
1241,2023-06,386834,19028,194814,-7515,-13294,491836,114618,0,801892
1242,2023-07,401726,19118,194899,3020,-14652,514541,118874,0,787240
1243,2023-08,404637,23491,217594,-19583,-19611,517364,128386,0,767629

In [228]:
print(df_US_OIL.columns)
df_US_OIL_Selected = df_US_OIL[['Date','U.S. Field Production of Crude Oil (Thousand Barrels)',
                                'U.S. Imports of Crude Oil (Thousand Barrels)', 'U.S. Exports of Crude Oil (Thousand Barrels)',
                                'U.S. Ending Stocks of Crude Oil (Thousand Barrels)']]

Index(['Date', 'U.S. Field Production of Crude Oil (Thousand Barrels)',
       'U.S. Transfers to Crude Oil Supply of Crude Oil(Thousand Barrels)',
       'U.S. Imports of Crude Oil (Thousand Barrels)',
       'U.S. Supply Adjustment of Crude Oil (Thousand Barrels)',
       'U.S. Crude Oil Stock Change (Thousand Barrels)',
       'U.S. Refinery and Blender Net Input of Crude Oil (Thousand Barrels)',
       'U.S. Exports of Crude Oil (Thousand Barrels)',
       'U.S. Product Supplied of Crude Oil (Thousand Barrels)',
       'U.S. Ending Stocks of Crude Oil (Thousand Barrels)'],
      dtype='object', name=1)

In [229]:
df_US_OIL_Selected

1,Date,U.S. Field Production of Crude Oil (Thousand Barrels),U.S. Imports of Crude Oil (Thousand Barrels),U.S. Exports of Crude Oil (Thousand Barrels),U.S. Ending Stocks of Crude Oil (Thousand Barrels)
0,1920-01,34008,6294,469,0
1,1920-02,33193,4940,853,0
2,1920-03,36171,6503,892,0
3,1920-04,34945,6186,693,0
4,1920-05,36622,6966,761,0
...,...,...,...,...,...
1239,2023-04,379500,185821,120265,823605
1240,2023-05,393513,200556,117467,815186
1241,2023-06,386834,194814,114618,801892
1242,2023-07,401726,194899,118874,787240
1243,2023-08,404637,217594,128386,767629

In [230]:
# Second, for the inflation dataframe, we apply the melt method and create a new date with the format '2023-08'.

df_inflation = pd.read_excel(current_directory+"\\Inflation table.xlsx")

print(df_inflation)


df_inflation = df_inflation[df_inflation['Year'].notna()]
df_inflation.drop(columns=['Ave'],inplace =True)
df_inflation['Year'] = df_inflation['Year'].astype(int).astype(str)

df_inflation_melt = df_inflation.melt(id_vars='Year', var_name='Month', value_name='Value')
df_inflation_melt['Date'] = df_inflation_melt['Year'] + '-' + df_inflation_melt['Month']
df_inflation_melt.drop(columns=['Year', 'Month'],inplace = True)

df_inflation_melt['Date'] = pd.to_datetime(df_inflation_melt['Date']).dt.strftime('%Y-%m')
df_inflation_melt.dropna()

       Year   Jan   Feb   Mar   Apr   May   Jun   Jul   Aug   Sep   Oct  \
0    1914.0   2.0   1.0   1.0   0.0   2.1   1.0   1.0   3.0   2.0   1.0
1    1915.0   1.0   1.0   0.0   2.0   2.0   2.0   1.0  -1.0  -1.0   1.0
2    1916.0   3.0   4.0   6.1   6.0   5.9   6.9   6.9   7.9   9.9  10.8
3    1917.0  12.5  15.4  14.3  18.9  19.6  20.4  18.5  19.3  19.8  19.5
4    1918.0  19.7  17.5  16.7  12.7  13.3  13.1  18.0  18.5  18.0  18.5
..      ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
107  2021.0   1.4   1.7   2.6   4.2   5.0   5.4   5.4   5.3   5.4   6.2
108  2022.0   7.5   7.9   8.5   8.3   8.6   9.1   8.5   8.3   8.2   7.7
109  2023.0   6.4   6.0   5.0   4.9   4.0   3.0   3.2   3.7   3.7   3.2
110     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
111     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN

        Nov   Dec   Ave
0       1.0   1.0   1.0
1       1.0   2.0   1.0
2      11.7  12.6   7.9
3      17.4  18.1  17.4
4      20.7  20.4  18.0
..      ...   ...   ...
107     6.8   7.0   4.7
108     7.1   6.5   8.0
109  Avail.   NaN   NaN
110    Dec.   NaN   NaN
111      12   NaN   NaN

[112 rows x 14 columns]

     Value     Date
0      2.0  1914-01
1      1.0  1915-01
2      3.0  1916-01
3     12.5  1917-01
4     19.7  1918-01
...    ...      ...
1314   1.9  2018-12
1315   2.3  2019-12
1316   1.4  2020-12
1317   7.0  2021-12
1318   6.5  2022-12

[1319 rows x 2 columns]

In [231]:
# Then, for the DFF dataframe, we group by Date and calculate the average DFF per month.

df_DFF = pd.read_csv(current_directory+"\\DFF.csv")
df_DFF['DATE'] =  pd.to_datetime(df_DFF['DATE']).dt.strftime('%Y-%m')
df_DFF = df_DFF.groupby(['DATE'])['DFF'].mean().round(2).reset_index()
df_DFF

        DATE   DFF
0    1954-07  0.80
1    1954-08  1.22
2    1954-09  1.07
3    1954-10  0.85
4    1954-11  0.83
..       ...   ...
828  2023-07  5.12
829  2023-08  5.33
830  2023-09  5.33
831  2023-10  5.33
832  2023-11  5.33

[833 rows x 2 columns]

In [232]:
# Finally, we merge all the dataframes.

df_merged = df_DFF.merge(df_inflation_melt, left_on = 'DATE', right_on = 'Date', how = 'left')
df_merged = df_merged.merge(df_US_OIL_Selected, on= 'Date', how = 'left')
df_merged = df_merged.dropna().drop(columns = ['DATE']).rename(columns = {'Value' : 'U.S. Inflation', 'DFF' : 'Federal Fund Effective Rate (DFF)'})

In [233]:
df_merged.to_csv(current_directory+'\inflation DFF OIL.csv',index = False)
df_merged

,Federal Fund Effective Rate (DFF),U.S. Inflation,Date,U.S. Field Production of Crude Oil (Thousand Barrels),U.S. Imports of Crude Oil (Thousand Barrels),U.S. Exports of Crude Oil (Thousand Barrels),U.S. Ending Stocks of Crude Oil (Thousand Barrels)
0,0.80,0.4,1954-07,194098.0,22448.0,1073.0,0.0
1,1.22,0.0,1954-08,190388.0,20589.0,1349.0,0.0
2,1.07,-0.4,1954-09,184325.0,20168.0,509.0,0.0
3,0.85,-0.7,1954-10,189724.0,19893.0,1521.0,0.0
4,0.83,-0.4,1954-11,190372.0,19082.0,1047.0,0.0
...,...,...,...,...,...,...,...
825,4.83,4.9,2023-04,379500.0,185821.0,120265.0,823605.0
826,5.06,4.0,2023-05,393513.0,200556.0,117467.0,815186.0
827,5.08,3.0,2023-06,386834.0,194814.0,114618.0,801892.0
828,5.12,3.2,2023-07,401726.0,194899.0,118874.0,787240.0
829,5.33,3.7,2023-08,404637.0,217594.0,128386.0,767629.0